//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Country
{
    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string PhoneNoFormat { get; set; }
    public string DialingCountryCode { get; set; }
    public string InternationalDialingCode { get; set; }
    public string InternetTLD { get; set; }
}

public partial class Customer
{
    public System.Guid ID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public string ZipCode { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public System.Guid CountryID { get; set; }
    public string EmailAddress { get; set; }
    public string Url { get; set; }
    public Nullable<int> CreditLimit { get; set; }
    public Nullable<bool> NewsSubscriber { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }
    public string ModifiedBy { get; set; }
}
